version: "3.8"
services:
  postgres:
    image: postgres:16.0-alpine3.17
    container_name: postgres-go
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=transx
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 3
    networks:
      - home

  backend:
    build: ./backend
    container_name: machnet-backend
    depends_on:
      postgres:
          condition: service_healthy
    ports:
      - "9000:9000"
    environment:
      - host=postgres
      - port=5432
      - username=postgres
      - password=test1234
      - dbname=transx
    networks:
      - home

networks:
  home:
    name: home